### ISSUE TITLE
Application filter does not work

### ISSUE THREAD

**Issue by StigLau** [Cantara/Whydah-UserAdminWebApp#1]
maurtvedt commented on Jun 27, 2014
The application filter next to the search box isn't working
 @maurtvedtmaurtvedt added the bug label on Jun 27, 2014
leon-ho commented on Jun 27, 2014
Requires a not-yet implemented API for Applications in UIB first.
 @leon-holeon-ho changed the title from Application filter is does not work to Application filter does not work on Jun 27, 2014

**Comment by totto** [comment]
API is implemented in HEAD in UIB and UAS)

**Comment by baardl** [comment]
This is a featrure yet not implemented.
