### ISSUE TITLE
500 Server error when trying to add role immediately after creating user

### ISSUE THREAD

**Issue by maurtvedt** [Cantara/Whydah-UserAdminWebApp#36]
Tested at https://whydahdev.cantara.no

To reproduce: 
- Click add user
- Fill out form and press save
- Click add role without closing the form
- Fill out role and press add role - crash with 500

(Workaround is to close the form and reopen it, then it works)

![image](https://cloud.githubusercontent.com/assets/5319548/11323356/a4f54f24-9110-11e5-8a5e-4181961b3092.png)

**Comment by totto** [comment]
The problem here is that UAWA must re-read the user to get the user UID before it can add roles, I see two solutions
# update the UID from new user POST to UAS
# close the pop-up window upon user creation
